# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'botbrain_feed_sdk_ios_demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # ignore all warnings from all pods
  inhibit_all_warnings!
  # Pods for botbrain_feed_sdk_ios_demo
  pod 'botbrain_feed_sdk_ios_lite', :path => '../'
  
end
